### ISSUE TITLE
Should I be using Bazel for all my projects?

### ISSUE THREAD

**Issue by owodunni** [tobyndax/AdventOfCode2021#4]
I like to use build systems but I find draging gradle into every new project to be a bit cumbersome. I always have to start out with a Java docker image in CI. Should I instead be using and trying out bazel?!

**Comment by tobyndax** [comment]
Should you try Bazel out? Yes! 
However, you should probably try it out with one of the languages it actually likes, i.e. python, c/c++, Java (https://docs.bazel.build/versions/4.2.2/be/overview.html) 

Without having used those parts of Bazel yet, I think gradle is more powerful in the "flexibility" department.
Not sure how good Bazel will be, once I need to general stuff, like moving / zipping some files, or uploading something to artifactory (or the like).  https://docs.bazel.build/versions/4.2.2/be/general.html#genrule

It's quite fixed structure for c++ and tests, is quite refreshing :)

**Comment by owodunni** [comment]
Nobody likes Java! Trying it out with Golang. So far so good!
